### ISSUE TITLE
Pause/Play stops mpDris2

### ISSUE THREAD

**Issue by perfect7gentleman** [eonpatapon/mpDris2#100]
```
$ mpDris2
2017-12-31 20:09:17,521 mpDris2 INFO: Using file:///home/userxxx/.config/mpd/music as music library path.
2017-12-31 20:09:17,521 mpDris2 INFO: Mutagen not available, covers in music files will be ignored.
2017-12-31 20:09:17,523 mpDris2 WARNING: Failed to connect to GNOME Settings Daemon. Media keys won't work.
2017-12-31 20:09:17,523 base INFO: Calling MPD connect('127.0.0.1', '6600', timeout=None)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 755, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/bin/mpDris2", line 466, in socket_callback
    data = fd._fetch_objects("changed")
  File "/usr/bin/mpDris2", line 856, in __getattr__
    raise AttributeError(attr)
AttributeError: _fetch_objects
Traceback (most recent call last):
  File "/usr/bin/mpDris2", line 453, in timer_callback
    self._update_properties(force=False)
  File "/usr/bin/mpDris2", line 728, in _update_properties
    if old_status['state'] != new_status['state']:
KeyError: 'state'
2017-12-31 20:12:53,173 mpDris2 WARNING: Disconnected
/usr/bin/mpDris2:388: Warning: Source ID 13 was not found when attempting to remove it
  GLib.source_remove(self._poll_id)
/usr/bin/mpDris2:391: Warning: Source ID 14 was not found when attempting to remove it
  GLib.source_remove(self._watch_id)
2017-12-31 20:12:53,177 base INFO: Calling MPD disconnect()
2017-12-31 20:12:53,177 base INFO: Calling MPD connect('127.0.0.1', '6600', timeout=None)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 755, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/bin/mpDris2", line 466, in socket_callback
    data = fd._fetch_objects("changed")
  File "/usr/bin/mpDris2", line 856, in __getattr__
    raise AttributeError(attr)
AttributeError: _fetch_objects
2017-12-31 20:12:58,434 mpDris2 WARNING: Disconnected
/usr/bin/mpDris2:391: Warning: Source ID 19 was not found when attempting to remove it
  GLib.source_remove(self._watch_id)
2017-12-31 20:12:58,442 base INFO: Calling MPD disconnect()
2017-12-31 20:12:58,442 base INFO: Calling MPD connect('127.0.0.1', '6600', timeout=None)
Traceback (most recent call last):
  File "/usr/bin/mpDris2", line 449, in timer_callback
    was_idle = self.idle_leave()
  File "/usr/bin/mpDris2", line 438, in idle_leave
    self._fetch_object()
  File "/usr/bin/mpDris2", line 856, in __getattr__
    raise AttributeError(attr)
AttributeError: _fetch_object
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GLib.py", line 755, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/bin/mpDris2", line 466, in socket_callback
    data = fd._fetch_objects("changed")
  File "/usr/bin/mpDris2", line 856, in __getattr__
    raise AttributeError(attr)
AttributeError: _fetch_objects
2017-12-31 20:13:33,183 mpDris2 INFO: Replaced by :1.388 (PID 9790)
2017-12-31 20:13:33,184 base INFO: Calling MPD disconnect()
```

**Comment by grawity** [comment]
What mpd version are you using, and what python-mpd version are you using?

**Comment by perfect7gentleman** [comment]
```
 ~ $ mpd --version
Music Player Daemon 0.20.13
```
python-mpd2 - git-version built with Python3.6

**Comment by grawity** [comment]
I assume "git-version" means something recent?
