### ISSUE TITLE
connection refused error when starting. 

### ISSUE THREAD

**Issue by Laar3** [eonpatapon/mpDris2#149]
when running "mpDris2" i get an error saying the connection has been refused.

```
2021-12-27 08:33:11,558 mpDris2 INFO: Using file:///home/spagett/music as music library path.
2021-12-27 08:33:11,558 mpDris2 INFO: Using Mutagen to read covers from music files.
Traceback (most recent call last):
  File "/usr/local/bin/mpDris2", line 1485, in <module>
    notification = NotifyWrapper(params)
  File "/usr/local/bin/mpDris2", line 912, in __init__
    self._notification = self._bootstrap_notifications()
  File "/usr/local/bin/mpDris2", line 920, in _bootstrap_notifications
    bus = dbus.SessionBus()
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-LTqYxdHLiE: Connection refused
```
im running artix openrc and my config file for it looks like this 
```
# Copy this to /etc/mpDris2.conf or ~/.config/mpDris2/mpDris2.conf
# Default values are shown here, commented out.

[Connection]
# You can also export $MPD_HOST and/or $MPD_PORT to change the server.
host = localhost
port = 6600
#password =

[Library]
music_dir = /home/spagett/music
#cover_regex = ^(album|cover|\.?folder|front).*\.(gif|jpeg|jpg|png)$

[Bling]
#mmkeys = True
#notify = True
# Urgency of the notification: 0 for low, 1 for medium and 2 for high.
#notify_urgency = 0
```

**Comment by grawity** [comment]
It sounds like your `dbus-daemon --session` process got killed, so $DBUS_SESSION_BUS_ADDRESS is now pointing to a nonexistent bus socket.

mpDris2 requires a working D-Bus session bus to function. If you aren't using systemd (with systemd --user), then make sure that your desktop is launched through `dbus-run-session` or, if that's not available, through `dbus-launch`.

**Comment by Laar3** [comment]
Yeah I'm on artix so running my wm with dbus-run-session fixed the issue. Thanks!
