### ISSUE TITLE
crash on startup when password is wrong

### ISSUE THREAD

**Issue by cweiske** [eonpatapon/mpDris2#75]
When starting mpDris2 0.7 on Ubuntu Linux 14.04 with 0.18.7-1 I get the following crash:

```
$ mpDris2 --debug
2016-07-01 21:24:57,026 mpDris2 INFO: Using file:///home/cweiske/Musik as music library path.
2016-07-01 21:24:57,027 mpDris2 INFO: Using Mutagen to read covers from music files.
2016-07-01 21:24:57,027 mpDris2 DEBUG: Using GObject-Introspection main loop.
2016-07-01 21:24:57,028 mpDris2 DEBUG: Initializing GObject.Notify
2016-07-01 21:24:57,040 mpDris2 WARNING: Failed to connect to GNOME Settings Daemon. Media keys won't work.
2016-07-01 21:24:57,043 mpDris2 DEBUG: Sending command 'password' (was idle? False)
2016-07-01 21:24:57,043 mpDris2 DEBUG: Trying to reconnect, got CommandError('[3@0] {password} incorrect password',)
2016-07-01 21:24:57,043 mpDris2 WARNING: Disconnected
Traceback (most recent call last):
  File "/usr/local/bin/mpDris2", line 1290, in <module>
    mpd_wrapper.run()
  File "/usr/local/bin/mpDris2", line 275, in run
    if self.my_connect():
  File "/usr/local/bin/mpDris2", line 290, in my_connect
    self.password(self._params['password'])
  File "/usr/local/bin/mpDris2", line 795, in fn
    return self.call(attr, *a, **kw)
  File "/usr/local/bin/mpDris2", line 810, in call
    self.reconnect()
  File "/usr/local/bin/mpDris2", line 362, in reconnect
    self._dbus_service.release_name()
AttributeError: 'bool' object has no attribute 'release_name'

```

This also happens with latest git master.

**Comment by cweiske** [comment]
`MPD_HOST` had a password, while my mpd did not have a password set. Thus the password was incorrect, and mpdris2 crashed.
