### ISSUE TITLE
systemd unit make systemd crash?

### ISSUE THREAD

**Issue by boyska** [eonpatapon/mpDris2#77]
I understand that it sounds weird, so it might totally be the case that  I am wrong here.

Anyway, that's my bug report:
- mpDris2 works fine for me. I can run it from a terminal and it works. yay.
- If I enable the provided `mpDris2.service`, it will crash, and... will make the whole systemd crash. Here is some log:

```
lug 28 08:58:07 systemd[2971]: Started Sound Service.
lug 28 08:58:08 mpDris2[3153]: Traceback (most recent call last):
lug 28 08:58:08 mpDris2[3153]:   File "/usr/bin/mpDris2", line 304, in my_connect
lug 28 08:58:08 mpDris2[3153]:     notification.notify(identity, _('Reconnected'))
lug 28 08:58:08 mpDris2[3153]:   File "/usr/bin/mpDris2", line 809, in notify
lug 28 08:58:08 mpDris2[3153]:     self._notification.show()
lug 28 08:58:08 mpDris2[3153]: GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifica
lug 28 08:58:21 org.a11y.Bus[3484]: Activating service name='org.a11y.atspi.Registry'
lug 28 08:58:21 org.a11y.Bus[3484]: ** (process:3490): WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: Th
lug 28 08:58:21 org.a11y.Bus[3484]: Successfully activated service 'org.a11y.atspi.Registry'
lug 28 08:58:21 org.a11y.atspi.Registry[3503]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
lug 28 08:58:23 awesome[3472]: restack_win(0x0080000b, 0x01000003): Failed to found new above window.
lug 28 08:58:23 awesome[3472]: restack_win(0x0080000b, 0x01000003): Failed to found new above window.
lug 28 08:59:19 systemd[2971]: Stopped target Default.
[omit some more Stopping/Stopped]
lug 28 08:59:19 systemd[2971]: Stopped target Timers.
lug 28 08:59:19 systemd[2971]: Stopped target Sockets.
lug 28 08:59:19 systemd[2971]: Closed D-Bus User Message Bus Socket.
lug 28 08:59:19 systemd[2971]: Closed Sound System.
lug 28 08:59:19 systemd[2971]: Reached target Shutdown.
lug 28 08:59:19 systemd[2971]: Starting Exit the Session...
lug 28 08:59:19 systemd[2971]: _Receied_ SIGRTMIN+24 from PID 4323 (kill).
lug 28 08:59:19 systemd[3108]: pam_unix(systemd-user:session): session closed for user user
```

I think that this is related to how systemd manages `BusName` directive, which I don't know

**Comment by grawity** [comment]
If systemd crashes – that is, if it _still_ crashes even with the latest release – then file a systemd bug report instead. (Or it might be dbus-daemon which is crashing; check dmesg and/or syslog.) Either way, not a mpDris2 issue.
