### ISSUE TITLE
Covers do not get sent

### ISSUE THREAD

**Issue by ArsenArsen** [eonpatapon/mpDris2#95]
Hello!
I have been using mpDris for a while, and I noticed that it does not send covers on songs, while Cantata, VLC, etc detect the covers fine. Below is my config:

```ini
[Connection]
music_dir = /home/arsen/Music/
```

I have even checked the log, and the directory is used,
Thanks

**Comment by grawity** [comment]
Do you have the Python `mutagen` module installed, and does mpDris2 mention it during startup?

**Comment by ArsenArsen** [comment]
Hello, 
Yes I do have mutagen installed.

Below is the full log:
```
Sep 11 19:38:22 arsen-pc systemd[1132]: Starting mpDris2 - Music Player Daemon D-Bus bridge...
Sep 11 19:38:24 arsen-pc mpDris2[1140]: 2017-09-11 19:38:24,042 mpDris2 INFO: Using file:///home/arsen/Music/ as music library path.
Sep 11 19:38:24 arsen-pc mpDris2[1140]: 2017-09-11 19:38:24,042 mpDris2 INFO: Using Mutagen to read covers from music files.
Sep 11 19:38:24 arsen-pc mpDris2[1140]: 2017-09-11 19:38:24,322 mpDris2 WARNING: Failed to connect to GNOME Settings Daemon. Media keys won't work.
Sep 11 19:38:26 arsen-pc systemd[1132]: Started mpDris2 - Music Player Daemon D-Bus bridge.
Sep 11 19:38:52 arsen-pc mpDris2[1140]: Traceback (most recent call last):
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 1290, in <module>
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     mpd_wrapper.run()
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 275, in run
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     if self.my_connect():
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 342, in my_connect
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     self.timer_callback()
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 432, in timer_callback
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     self._update_properties(force=False)
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 703, in _update_properties
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     self.notify_about_track(new_meta, new_status['state'])
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 591, in notify_about_track
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     notification.notify(title, body, uri)
Sep 11 19:38:52 arsen-pc mpDris2[1140]:   File "/usr/bin/mpDris2", line 838, in notify
Sep 11 19:38:52 arsen-pc mpDris2[1140]:     self._notification.show()
Sep 11 19:38:52 arsen-pc mpDris2[1140]: GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached (24)
Sep 11 19:39:04 arsen-pc systemd[1132]: mpDris2.service: Main process exited, code=exited, status=1/FAILURE
Sep 11 19:39:04 arsen-pc systemd[1132]: mpDris2.service: Unit entered failed state.
Sep 11 19:39:04 arsen-pc systemd[1132]: mpDris2.service: Failed with result 'exit-code'.
```
Sometimes the glib error does not happen though.

**Comment by grawity** [comment]
The glib error happens because you have desktop notifications enabled, but mpDris starts before the DE component which _shows_ those notifications. This could probably be improved, similar to g-s-d...
